language: node_js
script:
  - npm install
  - npm test
node_js:
  - 6.10
  - 8.11
  - 10.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  - CXX=g++-4.9
sudo: false
